import { NavItem } from '@/types';

export const GENESIS_FILES: NavItem[] = [
  {
    id: '1',
    label: 'NodesHub',
    target: '_blank',
    href: 'https://files.nodeshub.online/testnet/symphony/',
    description: 'The JSON and address book needed to start a node',
  },
  {
    id: '2',
    label: 'Polkachu',
    target: '_blank',
    href: 'https://polkachu.com/testnets/symphony/genesis',
    description: 'The JSON needed to start a node',
  },
  {
    id: '3',
    label: 'NodeStake',
    target: '_blank',
    href: 'https://ss-t.symphony.nodestake.org/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '4',
    label: 'KonsorTech',
    target: '_blank',
    href: 'https://snap2.konsortech.xyz/symphony/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '4',
    label: 'KonsorTech',
    target: '_blank',
    href: 'https://snap2.konsortech.xyz/symphony/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '5',
    label: 'Sychonix',
    target: '_blank',
    href: 'https://service.sychonix.com/testnet/symphony/genesis',
    description: 'The JSON needed to start a node',
  },
  {
    id: '6',
    label: 'SyaNodes',
    target: '_blank',
    href: 'https://testnet-files.syanodes.my.id/symphony-genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '7',
    label: 'CryptoNodeID',
    target: '_blank',
    href: 'https://snapshot.cryptonode.id/symphony-testnet/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '8',
    label: 'DashNode',
    target: '_blank',
    href: 'https://snapshot.dashnode.org/symphony-testnet/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '9',
    label: 'NodeSync',
    target: '_blank',
    href: 'https://files.nodesync.top/Symphony/symphony-genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '10',
    label: 'Ravenode',
    target: '_blank',
    href: 'https://snapshot.ravenode.xyz/symphony/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '11',
    label: 'Vinjan.Inc',
    target: '_blank',
    href: 'https://service.vinjan.xyz/testnet/symphony/genesis',
    description: 'The JSON needed to start a node',
  },
  {
    id: '12',
    label: 'CroutonDigital',
    target: '_blank',
    href: 'https://storage.crouton.digital/testnet/symphony/files/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '13',
    label: 'Node39.TOP',
    target: '_blank',
    href: 'https://node39.top/testnet/symphony/genesis.json',
    description: 'The JSON needed to start a node',
  },
  {
    id: '14',
    label: 'Winnode',
    target: '_blank',
    href: 'https://data.winnode.xyz/file/uploads/symphony_genesis.json',
    description: 'The JSON needed to start a node',
  },
];
