import { NavItem } from '@/types';

export const INSTALLATION_GUIDES: NavItem[] = [
  {
    id: '1',
    label: 'NodesHub',
    target: '_blank',
    href: 'https://services.nodeshub.online/testnet-networks/symphony/',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '2',
    label: 'NodeStake',
    target: '_blank',
    href: 'https://nodestake.org/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '3',
    label: 'NodeX Emperor',
    target: '_blank',
    href: 'https://docs.nodex.one/networks/testnet/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '4',
    label: 'Indonode',
    target: '_blank',
    href: 'https://indonode.net/services/testnet/symphony/installation#setup',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '5',
    label: 'KonsorTech',
    target: '_blank',
    href: 'https://konsortech.xyz/testnet/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '6',
    label: 'Sychonix',
    target: '_blank',
    href: 'https://service.sychonix.com/testnet/symphony/installation',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '7',
    label: 'SyaNodes',
    target: '_blank',
    href: 'https://docs.syanodes.my.id/symphony/node-installation',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '8',
    label: 'CryptoNodeID',
    target: '_blank',
    href: 'https://docs.cryptonode.id/en/testnet/symphony',
    description: 'Easy setup to start a validator',
  },
  {
    id: '9',
    label: 'DashNode',
    target: '_blank',
    href: 'https://services.dashnode.org/network/cosmos/symphony/installation',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '10',
    label: 'Ravenode',
    target: '_blank',
    href: 'https://docs.ravenode.xyz/testnet/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '11',
    label: 'Vinjan.Inc',
    target: '_blank',
    href: 'https://service.vinjan.xyz/testnet/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '12',
    label: 'CroutonDigital',
    target: '_blank',
    href: 'https://crouton.digital/services/testnets/symphony',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '13',
    label: 'Dnsarz',
    target: '_blank',
    href: 'https://dnsarz.xyz/services/testnet/symphony/installation/',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '14',
    label: 'CommunityNode',
    target: '_blank',
    href: 'https://comunity-node.gitbook.io/validator-tools',
    description: 'Documentation on how to start a validator',
  },
  {
    id: '15',
    label: 'Winnode',
    target: '_blank',
    href: 'https://docs.winnode.site/tesnet/symphony/install',
    description: 'Guide Instalation a validator',
  },
  {
    id: '16',
    label: 'KenZ|DragonVN',
    target: '_blank',
    href: 'https://docs.kzvn.xyz/cosmos/symphony',
    description: 'Guide Instalation a validator',
  },
  {
    id: '17',
    label: 'DANGGIA',
    target: '_blank',
    href: 'https://danggia.gitbook.io/guide/guide/symphony',
    description: 'Guide Instalation a validator',
  },
  {
    id: '18',
    label: 'Cogwheel ⚙️',
    target: '_blank',
    href: 'https://docs.cogwheel.zone/testnet/symphony-testnet/install-node',
    description: 'Guide to install node and set up the validator.',
  },
  {
    id: '19',
    label: 'Unity Nodes',
    target: '_blank',
    href: 'https://services.unitynodes.com/testnet-network/symphony-blockchain/installation',
    description: 'Guide to install node and set up the validator.',
  },
  {
    id: '20',
    label: 'Bang Pateng',
    target: '_blank',
    href: 'https://bangpateng.xyz/docs/Testnet/Symphony/install',
    description: 'Guide to install node and set up the validator.',
  },
  {
    id: '21',
    label: 'Shazoe',
    target: '_blank',
    href: 'https://services.shazoe.xyz/testnets/symphony/node-installation',
    description: 'Guide to install node and set up the validator.',
  },
  {
    id: '22',
    label: 'X1Nodes',
    target: '_blank',
    href: 'https://docs.x1node.xyz',
    description: 'Guide to install node and set up the validator.',
  },
    {
    id: '23',
    label: 'Shamura',
    target: '_blank',
    href: 'https://service.shamura.one/testnets/symphony/installation',
    description: 'Guide to install node and set up the validator.',
  },
];
