import { NavItem } from '@/types';

export const SNAPSHOTS: NavItem[] = [
  {
    id: '1',
    label: 'NodesHub',
    target: '_blank',
    href: 'https://files.nodeshub.online/testnet/symphony/snapshot/symphony_snap.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '2',
    label: 'Polkachu',
    target: '_blank',
    href: 'https://polkachu.com/testnets/symphony/snapshots',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '3',
    label: 'NodeStake',
    target: '_blank',
    href: 'https://ss-t.symphony.nodestake.org/2024-07-27_symphony_100519.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '4',
    label: 'Nodeist',
    target: '_blank',
    href: 'https://t-ss.nodeist.net/symphony/snapshot_latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '5',
    label: 'Nodex.one',
    target: '_blank',
    href: 'https://snap.nodex.one/symphony-testnet/symphony-latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '6',
    label: 'KonsorTech',
    target: '_blank',
    href: 'https://snap2.konsortech.xyz/symphony',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '7',
    label: 'Sychonix',
    target: '_blank',
    href: 'https://service.sychonix.com/testnet/symphony/snapshot',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '8',
    label: 'SyaNodes',
    target: '_blank',
    href: 'https://ss.syanodes.my.id/symphony/ss-symphony.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '9',
    label: 'CryptoNodeID',
    target: '_blank',
    href: 'https://docs.cryptonode.id/en/testnet/symphony/endpoints-and-sync',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '10',
    label: 'DashNode',
    target: '_blank',
    href: 'https://snapshot.dashnode.org/symphony-testnet/',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '11',
    label: 'NodeSync',
    target: '_blank',
    href: 'https://files.nodesync.top/Symphony/',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '12',
    label: 'Ravenode',
    target: '_blank',
    href: 'https://snapshot.ravenode.xyz/symphony/symphony-latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '13',
    label: 'Vinjan.Inc',
    target: '_blank',
    href: 'https://service.vinjan.xyz/testnet/symphony/snapshot',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '14',
    label: 'CroutonDigital',
    target: '_blank',
    href: 'https://storage.crouton.digital/testnet/symphony/snapshots/symphony_latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '15',
    label: 'Node39.TOP',
    target: '_blank',
    href: 'https://services.node39.top/index.html/cosmos/symphony/sync',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '16',
    label: 'Winnode',
    target: '_blank',
    href: 'https://data.winnode.xyz/file/uploads/symphony_snapshot_latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '17',
    label: 'Unity Nodes',
    target: '_blank',
    href: 'https://services.unitynodes.com/testnet-network/symphony-blockchain/sync/snapshots',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '18',
    label: 'Bang Pateng',
    target: '_blank',
    href: 'https://filex.bangpateng.xyz/snapshot/symphony/symphony-latest.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '19',
    label: 'Shazoe',
    target: '_blank',
    href: 'https://snapshot1.shazoe.xyz/testnet/snapshot1-symphony.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
  {
    id: '20',
    label: 'X1Nodes',
    target: '_blank',
    href: 'https://docs.x1node.xyz/snapshots',
    description: 'Snapshots to speed up validator synchronization',
  },
    {
    id: '21',
    label: 'Shamura',
    target: '_blank',
    href: 'https://snapshot.shamura.one/testnet/snapshot-symphony.tar.lz4',
    description: 'Snapshots to speed up validator synchronization',
  },
];
