import { NavItem } from '@/types';

export const EXPLORERS: NavItem[] = [
  {
    id: '1',
    label: 'Ping.pub',
    target: '_blank',
    href: 'https://testnet.ping.pub/symphony',
    description: 'The ping.pub explorer',
  },
  {
    id: '2',
    label: 'Cosmos Directory',
    target: '_blank',
    href: 'https://testnet.cosmos.directory/symphonytestnet',
    description: 'The interchain directory for the Cosmos ecosystem',
  },
  {
    id: '3',
    label: 'NodesHub',
    target: '_blank',
    href: 'https://testnet.explorer.nodeshub.online/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '4',
    label: 'NodeStake',
    target: '_blank',
    href: 'https://explorer.nodestake.org/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '5',
    label: 'Nodeist',
    target: '_blank',
    href: 'https://test.explorer.ist/Symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '6',
    label: 'NodeX Emperor',
    target: '_blank',
    href: 'https://explorer.nodex.one/symphony/staking/symphonyvaloper13ts3j8q27kcykenfzty7lre6gvgh8w62deuvme',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '7',
    label: 'Indonode',
    target: '_blank',
    href: 'https://explorer.indonode.net/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '8',
    label: 'KonsorTech',
    target: '_blank',
    href: 'https://testnet-explorer.konsortech.xyz/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '9',
    label: 'Sychonix',
    target: '_blank',
    href: 'https://explorer.sychonix.com/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '10',
    label: 'SyaNodes',
    target: '_blank',
    href: 'https://explorer.syanodes.my.id/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '11',
    label: 'Jhonswg',
    target: '_blank',
    href: 'https://explorer.jhonswg.com/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '12',
    label: 'CryptoNodeID',
    target: '_blank',
    href: 'https://testnet.cryptonode.id/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '13',
    label: 'NodeSync',
    target: '_blank',
    href: 'https://explorer.nodesync.top/Symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '14',
    label: 'Vinjan.Inc',
    target: '_blank',
    href: 'https://explorer.vinjan.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '15',
    label: 'Node39.TOP',
    target: '_blank',
    href: 'https://explorer.node39.top/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '16',
    label: 'Dnsarz',
    target: '_blank',
    href: 'https://ping.dnsarz.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '17',
    label: 'Winnode',
    target: '_blank',
    href: 'https://www.explorer.winnode.site/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '18',
    label: 'KenZ|DragonVN',
    target: '_blank',
    href: 'https://explorer.kzvn.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '19',
    label: 'ZONKOEK Testnet Explorer',
    target: '_blank',
    href: 'https://explorer-testnet.zonkoek.xyz',
    description: 'Explore the ZONKOEK testnet blockchain with up-to-date data.',
  },
  {
    id: '20',
    label: 'Cogwheel Explorer',
    target: '_blank',
    href: 'https://explorer.cogwheel.zone/symphony',
    description: 'An explorer from one of our supporting validators.',
  },
  {
    id: '21',
    label: 'X1NODE Explorer',
    target: '_blank',
    href: 'https://explorer-testnet.x1node.xyz',
    description: 'An explorer from one of our supporting validators.',
  },
    {
    id: '22',
    label: 'Shazoe Explorer',
    target: '_blank',
    href: 'https://explorer.shazoe.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators.',
  },
];
