import { NavItem } from '@/types';

export const EXPLORERS: NavItem[] = [
  {
    id: '1',
    label: 'Ping.pub',
    target: '_blank',
    href: 'https://testnet.ping.pub/symphony',
    description: 'The ping.pub explorer',
  },
  {
    id: '2',
    label: 'Cosmos Directory',
    target: '_blank',
    href: 'https://testnet.cosmos.directory/symphonytestnet',
    description: 'The interchain directory for the Cosmos ecosystem',
  },
  {
    id: '3',
    label: 'NodesHub',
    target: '_blank',
    href: 'https://testnet.explorer.nodeshub.online/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '4',
    label: 'Vinjan.Inc',
    target: '_blank',
    href: 'https://explorer.vinjan.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '5',
    label: 'Indonode',
    target: '_blank',
    href: 'https://explorer.indonode.net/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '6',
    label: 'SyaNodes',
    target: '_blank',
    href: 'https://explorer.syanodes.my.id/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '7',
    label: 'Jhonswg',
    target: '_blank',
    href: 'https://explorer.jhonswg.com/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '8',
    label: 'CryptoNodeID',
    target: '_blank',
    href: 'https://testnet.cryptonode.id/symphony',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '9',
    label: 'Dnsarz',
    target: '_blank',
    href: 'https://ping.dnsarz.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators',
  },
  {
    id: '10',
    label: 'Cogwheel Explorer',
    target: '_blank',
    href: 'https://explorer.cogwheel.zone/symphony',
    description: 'An explorer from one of our supporting validators.',
  },
  {
    id: '11',
    label: 'Shazoe Explorer',
    target: '_blank',
    href: 'https://explorer.shazoe.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators.',
  },
  {
    id: '12',
    label: 'Buster Explorer',
    target: '_blank',
    href: 'https://explorer.busternode.xyz/symphony-testnet',
    description: 'An explorer from one of our supporting validators.',
  },
];
